# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f20b5be92f7c07e250779795370fe3d10d541a0f24b02369e011e4d90418df0fe8e5f1ae574d7addcb30e4a2aa50a08e33cedc33d44ba1d212dc34173976d7da
  user_agent: securium
  hibp_api_key: f1f3bb22b5f44f169c48a70240a03dbf

test:
  secret_key_base: 31ec09a07d729303c78f24518839d2e024149d0991be381f05e603f6c9d9ae7d795e5efb08d9827776c8cf7c0f57edb9a806cad2dc6bd11a9521741dbb2efc93
  user_agent: securium
  hibp_api_key: f1f3bb22b5f44f169c48a70240a03dbf

qa:
  secret_key_base: 31ec09a07d729303c78f24518839d2e024149d0991be381f05e603f6c9d9ae7d795e5efb08d9827776c8cf7c0f57edb9a806cad2dc6bd11a9521741dbb2efc93
  user_agent: securium
  hibp_api_key: f1f3bb22b5f44f169c48a70240a03dbf

demo:
  secret_key_base: 31ec09a07d729303c78f24518839d2e024149d0991be381f05e603f6c9d9ae7d795e5efb08d9827776c8cf7c0f57edb9a806cad2dc6bd11a9521741dbb2efc93
  user_agent: securium
  hibp_api_key: f1f3bb22b5f44f169c48a70240a03dbf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  user_agent: <%= ENV["USER_AGENT"] %>
  hibp_api_key: <%= ENV["HIBP_API_KEY"] %>
